// flow-typed signature: 4c3adfb5df32453193ecd7163b6e0296
// flow-typed version: <<STUB>>/startaudiocontext_v^1.2.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'startaudiocontext'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'startaudiocontext' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'startaudiocontext/StartAudioContext' {
  declare module.exports: any;
}

// Filename aliases
declare module 'startaudiocontext/StartAudioContext.js' {
  declare module.exports: $Exports<'startaudiocontext/StartAudioContext'>;
}
