// flow-typed signature: d1fde2becebfb0d2dd4cf60fac24572e
// flow-typed version: <<STUB>>/tone_v^0.10.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tone'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tone' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tone/build/Tone' {
  declare module.exports: any;
}

declare module 'tone/build/Tone.min' {
  declare module.exports: any;
}

declare module 'tone/Tone/component/AmplitudeEnvelope' {
  declare module.exports: any;
}

declare module 'tone/Tone/component/Analyser' {
  declare module.exports: any;
}

declare module 'tone/Tone/component/Compressor' {
  declare module.exports: any;
}

declare module 'tone/Tone/component/CrossFade' {
  declare module.exports: any;
}

declare module 'tone/Tone/component/Envelope' {
  declare module.exports: any;
}

declare module 'tone/Tone/component/EQ3' {
  declare module.exports: any;
}

declare module 'tone/Tone/component/FeedbackCombFilter' {
  declare module.exports: any;
}

declare module 'tone/Tone/component/Filter' {
  declare module.exports: any;
}

declare module 'tone/Tone/component/Follower' {
  declare module.exports: any;
}

declare module 'tone/Tone/component/FrequencyEnvelope' {
  declare module.exports: any;
}

declare module 'tone/Tone/component/Gate' {
  declare module.exports: any;
}

declare module 'tone/Tone/component/LFO' {
  declare module.exports: any;
}

declare module 'tone/Tone/component/Limiter' {
  declare module.exports: any;
}

declare module 'tone/Tone/component/LowpassCombFilter' {
  declare module.exports: any;
}

declare module 'tone/Tone/component/Merge' {
  declare module.exports: any;
}

declare module 'tone/Tone/component/Meter' {
  declare module.exports: any;
}

declare module 'tone/Tone/component/MidSideCompressor' {
  declare module.exports: any;
}

declare module 'tone/Tone/component/MidSideMerge' {
  declare module.exports: any;
}

declare module 'tone/Tone/component/MidSideSplit' {
  declare module.exports: any;
}

declare module 'tone/Tone/component/Mono' {
  declare module.exports: any;
}

declare module 'tone/Tone/component/MultibandCompressor' {
  declare module.exports: any;
}

declare module 'tone/Tone/component/MultibandSplit' {
  declare module.exports: any;
}

declare module 'tone/Tone/component/Panner' {
  declare module.exports: any;
}

declare module 'tone/Tone/component/Panner3D' {
  declare module.exports: any;
}

declare module 'tone/Tone/component/PanVol' {
  declare module.exports: any;
}

declare module 'tone/Tone/component/ScaledEnvelope' {
  declare module.exports: any;
}

declare module 'tone/Tone/component/Split' {
  declare module.exports: any;
}

declare module 'tone/Tone/component/Volume' {
  declare module.exports: any;
}

declare module 'tone/Tone/control/CtrlInterpolate' {
  declare module.exports: any;
}

declare module 'tone/Tone/control/CtrlMarkov' {
  declare module.exports: any;
}

declare module 'tone/Tone/control/CtrlPattern' {
  declare module.exports: any;
}

declare module 'tone/Tone/control/CtrlRandom' {
  declare module.exports: any;
}

declare module 'tone/Tone/core/Buffer' {
  declare module.exports: any;
}

declare module 'tone/Tone/core/Buffers' {
  declare module.exports: any;
}

declare module 'tone/Tone/core/Bus' {
  declare module.exports: any;
}

declare module 'tone/Tone/core/Clock' {
  declare module.exports: any;
}

declare module 'tone/Tone/core/Context' {
  declare module.exports: any;
}

declare module 'tone/Tone/core/Delay' {
  declare module.exports: any;
}

declare module 'tone/Tone/core/Draw' {
  declare module.exports: any;
}

declare module 'tone/Tone/core/Emitter' {
  declare module.exports: any;
}

declare module 'tone/Tone/core/Gain' {
  declare module.exports: any;
}

declare module 'tone/Tone/core/IntervalTimeline' {
  declare module.exports: any;
}

declare module 'tone/Tone/core/Listener' {
  declare module.exports: any;
}

declare module 'tone/Tone/core/Master' {
  declare module.exports: any;
}

declare module 'tone/Tone/core/Offline' {
  declare module.exports: any;
}

declare module 'tone/Tone/core/OfflineContext' {
  declare module.exports: any;
}

declare module 'tone/Tone/core/Param' {
  declare module.exports: any;
}

declare module 'tone/Tone/core/Timeline' {
  declare module.exports: any;
}

declare module 'tone/Tone/core/TimelineState' {
  declare module.exports: any;
}

declare module 'tone/Tone/core/Tone' {
  declare module.exports: any;
}

declare module 'tone/Tone/core/Transport' {
  declare module.exports: any;
}

declare module 'tone/Tone/effect/AutoFilter' {
  declare module.exports: any;
}

declare module 'tone/Tone/effect/AutoPanner' {
  declare module.exports: any;
}

declare module 'tone/Tone/effect/AutoWah' {
  declare module.exports: any;
}

declare module 'tone/Tone/effect/BitCrusher' {
  declare module.exports: any;
}

declare module 'tone/Tone/effect/Chebyshev' {
  declare module.exports: any;
}

declare module 'tone/Tone/effect/Chorus' {
  declare module.exports: any;
}

declare module 'tone/Tone/effect/Convolver' {
  declare module.exports: any;
}

declare module 'tone/Tone/effect/Distortion' {
  declare module.exports: any;
}

declare module 'tone/Tone/effect/Effect' {
  declare module.exports: any;
}

declare module 'tone/Tone/effect/FeedbackDelay' {
  declare module.exports: any;
}

declare module 'tone/Tone/effect/FeedbackEffect' {
  declare module.exports: any;
}

declare module 'tone/Tone/effect/Freeverb' {
  declare module.exports: any;
}

declare module 'tone/Tone/effect/JCReverb' {
  declare module.exports: any;
}

declare module 'tone/Tone/effect/MidSideEffect' {
  declare module.exports: any;
}

declare module 'tone/Tone/effect/Phaser' {
  declare module.exports: any;
}

declare module 'tone/Tone/effect/PingPongDelay' {
  declare module.exports: any;
}

declare module 'tone/Tone/effect/PitchShift' {
  declare module.exports: any;
}

declare module 'tone/Tone/effect/StereoEffect' {
  declare module.exports: any;
}

declare module 'tone/Tone/effect/StereoFeedbackEffect' {
  declare module.exports: any;
}

declare module 'tone/Tone/effect/StereoWidener' {
  declare module.exports: any;
}

declare module 'tone/Tone/effect/StereoXFeedbackEffect' {
  declare module.exports: any;
}

declare module 'tone/Tone/effect/Tremolo' {
  declare module.exports: any;
}

declare module 'tone/Tone/effect/Vibrato' {
  declare module.exports: any;
}

declare module 'tone/Tone/event/Event' {
  declare module.exports: any;
}

declare module 'tone/Tone/event/Loop' {
  declare module.exports: any;
}

declare module 'tone/Tone/event/Part' {
  declare module.exports: any;
}

declare module 'tone/Tone/event/Pattern' {
  declare module.exports: any;
}

declare module 'tone/Tone/event/Sequence' {
  declare module.exports: any;
}

declare module 'tone/Tone/instrument/AMSynth' {
  declare module.exports: any;
}

declare module 'tone/Tone/instrument/DuoSynth' {
  declare module.exports: any;
}

declare module 'tone/Tone/instrument/FMSynth' {
  declare module.exports: any;
}

declare module 'tone/Tone/instrument/Instrument' {
  declare module.exports: any;
}

declare module 'tone/Tone/instrument/MembraneSynth' {
  declare module.exports: any;
}

declare module 'tone/Tone/instrument/MetalSynth' {
  declare module.exports: any;
}

declare module 'tone/Tone/instrument/Monophonic' {
  declare module.exports: any;
}

declare module 'tone/Tone/instrument/MonoSynth' {
  declare module.exports: any;
}

declare module 'tone/Tone/instrument/NoiseSynth' {
  declare module.exports: any;
}

declare module 'tone/Tone/instrument/PluckSynth' {
  declare module.exports: any;
}

declare module 'tone/Tone/instrument/PolySynth' {
  declare module.exports: any;
}

declare module 'tone/Tone/instrument/Sampler' {
  declare module.exports: any;
}

declare module 'tone/Tone/instrument/Synth' {
  declare module.exports: any;
}

declare module 'tone/Tone/signal/Abs' {
  declare module.exports: any;
}

declare module 'tone/Tone/signal/Add' {
  declare module.exports: any;
}

declare module 'tone/Tone/signal/AudioToGain' {
  declare module.exports: any;
}

declare module 'tone/Tone/signal/EqualPowerGain' {
  declare module.exports: any;
}

declare module 'tone/Tone/signal/Expr' {
  declare module.exports: any;
}

declare module 'tone/Tone/signal/GainToAudio' {
  declare module.exports: any;
}

declare module 'tone/Tone/signal/GreaterThan' {
  declare module.exports: any;
}

declare module 'tone/Tone/signal/GreaterThanZero' {
  declare module.exports: any;
}

declare module 'tone/Tone/signal/Modulo' {
  declare module.exports: any;
}

declare module 'tone/Tone/signal/Multiply' {
  declare module.exports: any;
}

declare module 'tone/Tone/signal/Negate' {
  declare module.exports: any;
}

declare module 'tone/Tone/signal/Normalize' {
  declare module.exports: any;
}

declare module 'tone/Tone/signal/Pow' {
  declare module.exports: any;
}

declare module 'tone/Tone/signal/Scale' {
  declare module.exports: any;
}

declare module 'tone/Tone/signal/ScaleExp' {
  declare module.exports: any;
}

declare module 'tone/Tone/signal/Signal' {
  declare module.exports: any;
}

declare module 'tone/Tone/signal/SignalBase' {
  declare module.exports: any;
}

declare module 'tone/Tone/signal/Subtract' {
  declare module.exports: any;
}

declare module 'tone/Tone/signal/TimelineSignal' {
  declare module.exports: any;
}

declare module 'tone/Tone/signal/WaveShaper' {
  declare module.exports: any;
}

declare module 'tone/Tone/signal/Zero' {
  declare module.exports: any;
}

declare module 'tone/Tone/source/AMOscillator' {
  declare module.exports: any;
}

declare module 'tone/Tone/source/BufferSource' {
  declare module.exports: any;
}

declare module 'tone/Tone/source/FatOscillator' {
  declare module.exports: any;
}

declare module 'tone/Tone/source/FMOscillator' {
  declare module.exports: any;
}

declare module 'tone/Tone/source/GrainPlayer' {
  declare module.exports: any;
}

declare module 'tone/Tone/source/MultiPlayer' {
  declare module.exports: any;
}

declare module 'tone/Tone/source/Noise' {
  declare module.exports: any;
}

declare module 'tone/Tone/source/OmniOscillator' {
  declare module.exports: any;
}

declare module 'tone/Tone/source/Oscillator' {
  declare module.exports: any;
}

declare module 'tone/Tone/source/Player' {
  declare module.exports: any;
}

declare module 'tone/Tone/source/PulseOscillator' {
  declare module.exports: any;
}

declare module 'tone/Tone/source/PWMOscillator' {
  declare module.exports: any;
}

declare module 'tone/Tone/source/Source' {
  declare module.exports: any;
}

declare module 'tone/Tone/source/UserMedia' {
  declare module.exports: any;
}

declare module 'tone/Tone/type/Frequency' {
  declare module.exports: any;
}

declare module 'tone/Tone/type/Time' {
  declare module.exports: any;
}

declare module 'tone/Tone/type/TimeBase' {
  declare module.exports: any;
}

declare module 'tone/Tone/type/TransportTime' {
  declare module.exports: any;
}

declare module 'tone/Tone/type/Type' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tone/build/Tone.js' {
  declare module.exports: $Exports<'tone/build/Tone'>;
}
declare module 'tone/build/Tone.min.js' {
  declare module.exports: $Exports<'tone/build/Tone.min'>;
}
declare module 'tone/Tone/component/AmplitudeEnvelope.js' {
  declare module.exports: $Exports<'tone/Tone/component/AmplitudeEnvelope'>;
}
declare module 'tone/Tone/component/Analyser.js' {
  declare module.exports: $Exports<'tone/Tone/component/Analyser'>;
}
declare module 'tone/Tone/component/Compressor.js' {
  declare module.exports: $Exports<'tone/Tone/component/Compressor'>;
}
declare module 'tone/Tone/component/CrossFade.js' {
  declare module.exports: $Exports<'tone/Tone/component/CrossFade'>;
}
declare module 'tone/Tone/component/Envelope.js' {
  declare module.exports: $Exports<'tone/Tone/component/Envelope'>;
}
declare module 'tone/Tone/component/EQ3.js' {
  declare module.exports: $Exports<'tone/Tone/component/EQ3'>;
}
declare module 'tone/Tone/component/FeedbackCombFilter.js' {
  declare module.exports: $Exports<'tone/Tone/component/FeedbackCombFilter'>;
}
declare module 'tone/Tone/component/Filter.js' {
  declare module.exports: $Exports<'tone/Tone/component/Filter'>;
}
declare module 'tone/Tone/component/Follower.js' {
  declare module.exports: $Exports<'tone/Tone/component/Follower'>;
}
declare module 'tone/Tone/component/FrequencyEnvelope.js' {
  declare module.exports: $Exports<'tone/Tone/component/FrequencyEnvelope'>;
}
declare module 'tone/Tone/component/Gate.js' {
  declare module.exports: $Exports<'tone/Tone/component/Gate'>;
}
declare module 'tone/Tone/component/LFO.js' {
  declare module.exports: $Exports<'tone/Tone/component/LFO'>;
}
declare module 'tone/Tone/component/Limiter.js' {
  declare module.exports: $Exports<'tone/Tone/component/Limiter'>;
}
declare module 'tone/Tone/component/LowpassCombFilter.js' {
  declare module.exports: $Exports<'tone/Tone/component/LowpassCombFilter'>;
}
declare module 'tone/Tone/component/Merge.js' {
  declare module.exports: $Exports<'tone/Tone/component/Merge'>;
}
declare module 'tone/Tone/component/Meter.js' {
  declare module.exports: $Exports<'tone/Tone/component/Meter'>;
}
declare module 'tone/Tone/component/MidSideCompressor.js' {
  declare module.exports: $Exports<'tone/Tone/component/MidSideCompressor'>;
}
declare module 'tone/Tone/component/MidSideMerge.js' {
  declare module.exports: $Exports<'tone/Tone/component/MidSideMerge'>;
}
declare module 'tone/Tone/component/MidSideSplit.js' {
  declare module.exports: $Exports<'tone/Tone/component/MidSideSplit'>;
}
declare module 'tone/Tone/component/Mono.js' {
  declare module.exports: $Exports<'tone/Tone/component/Mono'>;
}
declare module 'tone/Tone/component/MultibandCompressor.js' {
  declare module.exports: $Exports<'tone/Tone/component/MultibandCompressor'>;
}
declare module 'tone/Tone/component/MultibandSplit.js' {
  declare module.exports: $Exports<'tone/Tone/component/MultibandSplit'>;
}
declare module 'tone/Tone/component/Panner.js' {
  declare module.exports: $Exports<'tone/Tone/component/Panner'>;
}
declare module 'tone/Tone/component/Panner3D.js' {
  declare module.exports: $Exports<'tone/Tone/component/Panner3D'>;
}
declare module 'tone/Tone/component/PanVol.js' {
  declare module.exports: $Exports<'tone/Tone/component/PanVol'>;
}
declare module 'tone/Tone/component/ScaledEnvelope.js' {
  declare module.exports: $Exports<'tone/Tone/component/ScaledEnvelope'>;
}
declare module 'tone/Tone/component/Split.js' {
  declare module.exports: $Exports<'tone/Tone/component/Split'>;
}
declare module 'tone/Tone/component/Volume.js' {
  declare module.exports: $Exports<'tone/Tone/component/Volume'>;
}
declare module 'tone/Tone/control/CtrlInterpolate.js' {
  declare module.exports: $Exports<'tone/Tone/control/CtrlInterpolate'>;
}
declare module 'tone/Tone/control/CtrlMarkov.js' {
  declare module.exports: $Exports<'tone/Tone/control/CtrlMarkov'>;
}
declare module 'tone/Tone/control/CtrlPattern.js' {
  declare module.exports: $Exports<'tone/Tone/control/CtrlPattern'>;
}
declare module 'tone/Tone/control/CtrlRandom.js' {
  declare module.exports: $Exports<'tone/Tone/control/CtrlRandom'>;
}
declare module 'tone/Tone/core/Buffer.js' {
  declare module.exports: $Exports<'tone/Tone/core/Buffer'>;
}
declare module 'tone/Tone/core/Buffers.js' {
  declare module.exports: $Exports<'tone/Tone/core/Buffers'>;
}
declare module 'tone/Tone/core/Bus.js' {
  declare module.exports: $Exports<'tone/Tone/core/Bus'>;
}
declare module 'tone/Tone/core/Clock.js' {
  declare module.exports: $Exports<'tone/Tone/core/Clock'>;
}
declare module 'tone/Tone/core/Context.js' {
  declare module.exports: $Exports<'tone/Tone/core/Context'>;
}
declare module 'tone/Tone/core/Delay.js' {
  declare module.exports: $Exports<'tone/Tone/core/Delay'>;
}
declare module 'tone/Tone/core/Draw.js' {
  declare module.exports: $Exports<'tone/Tone/core/Draw'>;
}
declare module 'tone/Tone/core/Emitter.js' {
  declare module.exports: $Exports<'tone/Tone/core/Emitter'>;
}
declare module 'tone/Tone/core/Gain.js' {
  declare module.exports: $Exports<'tone/Tone/core/Gain'>;
}
declare module 'tone/Tone/core/IntervalTimeline.js' {
  declare module.exports: $Exports<'tone/Tone/core/IntervalTimeline'>;
}
declare module 'tone/Tone/core/Listener.js' {
  declare module.exports: $Exports<'tone/Tone/core/Listener'>;
}
declare module 'tone/Tone/core/Master.js' {
  declare module.exports: $Exports<'tone/Tone/core/Master'>;
}
declare module 'tone/Tone/core/Offline.js' {
  declare module.exports: $Exports<'tone/Tone/core/Offline'>;
}
declare module 'tone/Tone/core/OfflineContext.js' {
  declare module.exports: $Exports<'tone/Tone/core/OfflineContext'>;
}
declare module 'tone/Tone/core/Param.js' {
  declare module.exports: $Exports<'tone/Tone/core/Param'>;
}
declare module 'tone/Tone/core/Timeline.js' {
  declare module.exports: $Exports<'tone/Tone/core/Timeline'>;
}
declare module 'tone/Tone/core/TimelineState.js' {
  declare module.exports: $Exports<'tone/Tone/core/TimelineState'>;
}
declare module 'tone/Tone/core/Tone.js' {
  declare module.exports: $Exports<'tone/Tone/core/Tone'>;
}
declare module 'tone/Tone/core/Transport.js' {
  declare module.exports: $Exports<'tone/Tone/core/Transport'>;
}
declare module 'tone/Tone/effect/AutoFilter.js' {
  declare module.exports: $Exports<'tone/Tone/effect/AutoFilter'>;
}
declare module 'tone/Tone/effect/AutoPanner.js' {
  declare module.exports: $Exports<'tone/Tone/effect/AutoPanner'>;
}
declare module 'tone/Tone/effect/AutoWah.js' {
  declare module.exports: $Exports<'tone/Tone/effect/AutoWah'>;
}
declare module 'tone/Tone/effect/BitCrusher.js' {
  declare module.exports: $Exports<'tone/Tone/effect/BitCrusher'>;
}
declare module 'tone/Tone/effect/Chebyshev.js' {
  declare module.exports: $Exports<'tone/Tone/effect/Chebyshev'>;
}
declare module 'tone/Tone/effect/Chorus.js' {
  declare module.exports: $Exports<'tone/Tone/effect/Chorus'>;
}
declare module 'tone/Tone/effect/Convolver.js' {
  declare module.exports: $Exports<'tone/Tone/effect/Convolver'>;
}
declare module 'tone/Tone/effect/Distortion.js' {
  declare module.exports: $Exports<'tone/Tone/effect/Distortion'>;
}
declare module 'tone/Tone/effect/Effect.js' {
  declare module.exports: $Exports<'tone/Tone/effect/Effect'>;
}
declare module 'tone/Tone/effect/FeedbackDelay.js' {
  declare module.exports: $Exports<'tone/Tone/effect/FeedbackDelay'>;
}
declare module 'tone/Tone/effect/FeedbackEffect.js' {
  declare module.exports: $Exports<'tone/Tone/effect/FeedbackEffect'>;
}
declare module 'tone/Tone/effect/Freeverb.js' {
  declare module.exports: $Exports<'tone/Tone/effect/Freeverb'>;
}
declare module 'tone/Tone/effect/JCReverb.js' {
  declare module.exports: $Exports<'tone/Tone/effect/JCReverb'>;
}
declare module 'tone/Tone/effect/MidSideEffect.js' {
  declare module.exports: $Exports<'tone/Tone/effect/MidSideEffect'>;
}
declare module 'tone/Tone/effect/Phaser.js' {
  declare module.exports: $Exports<'tone/Tone/effect/Phaser'>;
}
declare module 'tone/Tone/effect/PingPongDelay.js' {
  declare module.exports: $Exports<'tone/Tone/effect/PingPongDelay'>;
}
declare module 'tone/Tone/effect/PitchShift.js' {
  declare module.exports: $Exports<'tone/Tone/effect/PitchShift'>;
}
declare module 'tone/Tone/effect/StereoEffect.js' {
  declare module.exports: $Exports<'tone/Tone/effect/StereoEffect'>;
}
declare module 'tone/Tone/effect/StereoFeedbackEffect.js' {
  declare module.exports: $Exports<'tone/Tone/effect/StereoFeedbackEffect'>;
}
declare module 'tone/Tone/effect/StereoWidener.js' {
  declare module.exports: $Exports<'tone/Tone/effect/StereoWidener'>;
}
declare module 'tone/Tone/effect/StereoXFeedbackEffect.js' {
  declare module.exports: $Exports<'tone/Tone/effect/StereoXFeedbackEffect'>;
}
declare module 'tone/Tone/effect/Tremolo.js' {
  declare module.exports: $Exports<'tone/Tone/effect/Tremolo'>;
}
declare module 'tone/Tone/effect/Vibrato.js' {
  declare module.exports: $Exports<'tone/Tone/effect/Vibrato'>;
}
declare module 'tone/Tone/event/Event.js' {
  declare module.exports: $Exports<'tone/Tone/event/Event'>;
}
declare module 'tone/Tone/event/Loop.js' {
  declare module.exports: $Exports<'tone/Tone/event/Loop'>;
}
declare module 'tone/Tone/event/Part.js' {
  declare module.exports: $Exports<'tone/Tone/event/Part'>;
}
declare module 'tone/Tone/event/Pattern.js' {
  declare module.exports: $Exports<'tone/Tone/event/Pattern'>;
}
declare module 'tone/Tone/event/Sequence.js' {
  declare module.exports: $Exports<'tone/Tone/event/Sequence'>;
}
declare module 'tone/Tone/instrument/AMSynth.js' {
  declare module.exports: $Exports<'tone/Tone/instrument/AMSynth'>;
}
declare module 'tone/Tone/instrument/DuoSynth.js' {
  declare module.exports: $Exports<'tone/Tone/instrument/DuoSynth'>;
}
declare module 'tone/Tone/instrument/FMSynth.js' {
  declare module.exports: $Exports<'tone/Tone/instrument/FMSynth'>;
}
declare module 'tone/Tone/instrument/Instrument.js' {
  declare module.exports: $Exports<'tone/Tone/instrument/Instrument'>;
}
declare module 'tone/Tone/instrument/MembraneSynth.js' {
  declare module.exports: $Exports<'tone/Tone/instrument/MembraneSynth'>;
}
declare module 'tone/Tone/instrument/MetalSynth.js' {
  declare module.exports: $Exports<'tone/Tone/instrument/MetalSynth'>;
}
declare module 'tone/Tone/instrument/Monophonic.js' {
  declare module.exports: $Exports<'tone/Tone/instrument/Monophonic'>;
}
declare module 'tone/Tone/instrument/MonoSynth.js' {
  declare module.exports: $Exports<'tone/Tone/instrument/MonoSynth'>;
}
declare module 'tone/Tone/instrument/NoiseSynth.js' {
  declare module.exports: $Exports<'tone/Tone/instrument/NoiseSynth'>;
}
declare module 'tone/Tone/instrument/PluckSynth.js' {
  declare module.exports: $Exports<'tone/Tone/instrument/PluckSynth'>;
}
declare module 'tone/Tone/instrument/PolySynth.js' {
  declare module.exports: $Exports<'tone/Tone/instrument/PolySynth'>;
}
declare module 'tone/Tone/instrument/Sampler.js' {
  declare module.exports: $Exports<'tone/Tone/instrument/Sampler'>;
}
declare module 'tone/Tone/instrument/Synth.js' {
  declare module.exports: $Exports<'tone/Tone/instrument/Synth'>;
}
declare module 'tone/Tone/signal/Abs.js' {
  declare module.exports: $Exports<'tone/Tone/signal/Abs'>;
}
declare module 'tone/Tone/signal/Add.js' {
  declare module.exports: $Exports<'tone/Tone/signal/Add'>;
}
declare module 'tone/Tone/signal/AudioToGain.js' {
  declare module.exports: $Exports<'tone/Tone/signal/AudioToGain'>;
}
declare module 'tone/Tone/signal/EqualPowerGain.js' {
  declare module.exports: $Exports<'tone/Tone/signal/EqualPowerGain'>;
}
declare module 'tone/Tone/signal/Expr.js' {
  declare module.exports: $Exports<'tone/Tone/signal/Expr'>;
}
declare module 'tone/Tone/signal/GainToAudio.js' {
  declare module.exports: $Exports<'tone/Tone/signal/GainToAudio'>;
}
declare module 'tone/Tone/signal/GreaterThan.js' {
  declare module.exports: $Exports<'tone/Tone/signal/GreaterThan'>;
}
declare module 'tone/Tone/signal/GreaterThanZero.js' {
  declare module.exports: $Exports<'tone/Tone/signal/GreaterThanZero'>;
}
declare module 'tone/Tone/signal/Modulo.js' {
  declare module.exports: $Exports<'tone/Tone/signal/Modulo'>;
}
declare module 'tone/Tone/signal/Multiply.js' {
  declare module.exports: $Exports<'tone/Tone/signal/Multiply'>;
}
declare module 'tone/Tone/signal/Negate.js' {
  declare module.exports: $Exports<'tone/Tone/signal/Negate'>;
}
declare module 'tone/Tone/signal/Normalize.js' {
  declare module.exports: $Exports<'tone/Tone/signal/Normalize'>;
}
declare module 'tone/Tone/signal/Pow.js' {
  declare module.exports: $Exports<'tone/Tone/signal/Pow'>;
}
declare module 'tone/Tone/signal/Scale.js' {
  declare module.exports: $Exports<'tone/Tone/signal/Scale'>;
}
declare module 'tone/Tone/signal/ScaleExp.js' {
  declare module.exports: $Exports<'tone/Tone/signal/ScaleExp'>;
}
declare module 'tone/Tone/signal/Signal.js' {
  declare module.exports: $Exports<'tone/Tone/signal/Signal'>;
}
declare module 'tone/Tone/signal/SignalBase.js' {
  declare module.exports: $Exports<'tone/Tone/signal/SignalBase'>;
}
declare module 'tone/Tone/signal/Subtract.js' {
  declare module.exports: $Exports<'tone/Tone/signal/Subtract'>;
}
declare module 'tone/Tone/signal/TimelineSignal.js' {
  declare module.exports: $Exports<'tone/Tone/signal/TimelineSignal'>;
}
declare module 'tone/Tone/signal/WaveShaper.js' {
  declare module.exports: $Exports<'tone/Tone/signal/WaveShaper'>;
}
declare module 'tone/Tone/signal/Zero.js' {
  declare module.exports: $Exports<'tone/Tone/signal/Zero'>;
}
declare module 'tone/Tone/source/AMOscillator.js' {
  declare module.exports: $Exports<'tone/Tone/source/AMOscillator'>;
}
declare module 'tone/Tone/source/BufferSource.js' {
  declare module.exports: $Exports<'tone/Tone/source/BufferSource'>;
}
declare module 'tone/Tone/source/FatOscillator.js' {
  declare module.exports: $Exports<'tone/Tone/source/FatOscillator'>;
}
declare module 'tone/Tone/source/FMOscillator.js' {
  declare module.exports: $Exports<'tone/Tone/source/FMOscillator'>;
}
declare module 'tone/Tone/source/GrainPlayer.js' {
  declare module.exports: $Exports<'tone/Tone/source/GrainPlayer'>;
}
declare module 'tone/Tone/source/MultiPlayer.js' {
  declare module.exports: $Exports<'tone/Tone/source/MultiPlayer'>;
}
declare module 'tone/Tone/source/Noise.js' {
  declare module.exports: $Exports<'tone/Tone/source/Noise'>;
}
declare module 'tone/Tone/source/OmniOscillator.js' {
  declare module.exports: $Exports<'tone/Tone/source/OmniOscillator'>;
}
declare module 'tone/Tone/source/Oscillator.js' {
  declare module.exports: $Exports<'tone/Tone/source/Oscillator'>;
}
declare module 'tone/Tone/source/Player.js' {
  declare module.exports: $Exports<'tone/Tone/source/Player'>;
}
declare module 'tone/Tone/source/PulseOscillator.js' {
  declare module.exports: $Exports<'tone/Tone/source/PulseOscillator'>;
}
declare module 'tone/Tone/source/PWMOscillator.js' {
  declare module.exports: $Exports<'tone/Tone/source/PWMOscillator'>;
}
declare module 'tone/Tone/source/Source.js' {
  declare module.exports: $Exports<'tone/Tone/source/Source'>;
}
declare module 'tone/Tone/source/UserMedia.js' {
  declare module.exports: $Exports<'tone/Tone/source/UserMedia'>;
}
declare module 'tone/Tone/type/Frequency.js' {
  declare module.exports: $Exports<'tone/Tone/type/Frequency'>;
}
declare module 'tone/Tone/type/Time.js' {
  declare module.exports: $Exports<'tone/Tone/type/Time'>;
}
declare module 'tone/Tone/type/TimeBase.js' {
  declare module.exports: $Exports<'tone/Tone/type/TimeBase'>;
}
declare module 'tone/Tone/type/TransportTime.js' {
  declare module.exports: $Exports<'tone/Tone/type/TransportTime'>;
}
declare module 'tone/Tone/type/Type.js' {
  declare module.exports: $Exports<'tone/Tone/type/Type'>;
}
